#--Server Settings--#
server:
  port: 8080

#--Security Settings--#
security:
  oauth2:
    client:
      clientId: 309619382850214
      clientSecret: 57a90adf5444f125b7ee0774393862a4
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me